#!/usr/bin/env Rscript

args_full <- commandArgs(trailingOnly = FALSE)
file_arg <- grep("^--file=", args_full, value = TRUE)
script_path <- if (length(file_arg)) {
  normalizePath(sub("^--file=", "", file_arg[[1L]]), mustWork = TRUE)
} else {
  normalizePath("scripts/robustness/generate_simulation_bundles.R", mustWork = TRUE)
}
repo_root <- normalizePath(file.path(dirname(script_path), "..", ".."), mustWork = TRUE)
source(file.path(dirname(script_path), "simulation_core.R"), local = FALSE)

required_packages <- c("digest", "jsonlite")
missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]
if (length(missing_packages)) {
  stop("Missing required package(s): ", paste(missing_packages, collapse = ", "))
}

sha256_file <- function(path) {
  digest::digest(path, algo = "sha256", file = TRUE)
}

sha256_object <- function(object) {
  digest::digest(object, algo = "sha256", serialize = TRUE)
}

read_seed_manifest <- function(path) {
  if (!file.exists(path)) stop("Seed manifest is missing: ", path, call. = FALSE)
  manifest <- read.csv(path, stringsAsFactors = FALSE, check.names = FALSE)
  required <- c(
    "workstream", "seed_id", "display_realization", "component", "seed",
    "prespecified_before_pilot"
  )
  missing <- setdiff(required, names(manifest))
  if (length(missing)) {
    stop("Seed manifest lacks column(s): ", paste(missing, collapse = ", "), call. = FALSE)
  }
  manifest
}

simulation_ledger_for <- function(seed_manifest, seed_id) {
  rows <- seed_manifest[
    seed_manifest$workstream == "canonical_repeated_simulation" &
      seed_manifest$seed_id == seed_id,
    ,
    drop = FALSE
  ]
  if (!nrow(rows)) stop("No canonical seed ledger rows found for ", seed_id, call. = FALSE)
  if (anyDuplicated(rows$component)) {
    stop("Duplicate component rows in seed ledger for ", seed_id, call. = FALSE)
  }
  rows
}

# The historical display files were generated by simulate_metabolomics.R with
# these six seeds.  The prespecified robustness ledger was captured later and
# contains different SIM01 generator seeds.  To satisfy the audited requirement
# that the display realization exactly reproduce the historical matrices, the
# bundle records both declared and effective seeds and overrides only these six
# SIM01 components.  SIM02--SIM30 use their declared ledger seeds unchanged.
legacy_sim01_generation_seeds <- c(
  clean_truth = 20260311L,
  batch_assignment = 20260312L,
  batch_magnitude = 20260313L,
  drift_assignment = 20260314L,
  drift_morphology = 20260315L,
  drift_shape = 20260316L
)

effective_ledger_for <- function(seed_manifest, seed_id) {
  ledger <- simulation_ledger_for(seed_manifest, seed_id)
  ledger$declared_seed <- as.integer(ledger$seed)
  ledger$effective_seed <- ledger$declared_seed
  ledger$seed_source <- "prespecified_seed_manifest"

  if (identical(seed_id, "SIM01")) {
    override <- match(ledger$component, names(legacy_sim01_generation_seeds))
    use_override <- !is.na(override)
    ledger$effective_seed[use_override] <- unname(
      legacy_sim01_generation_seeds[override[use_override]]
    )
    ledger$seed_source[use_override] <- "historical_display_compatibility"
  }
  ledger
}

validate_existing_bundle <- function(bundle_dir, expected_config_hash) {
  file_manifest_path <- file.path(bundle_dir, "bundle_files.csv")
  provenance_path <- file.path(bundle_dir, "bundle_provenance.json")
  if (!file.exists(file_manifest_path) || !file.exists(provenance_path)) return(FALSE)

  provenance <- tryCatch(
    jsonlite::read_json(provenance_path, simplifyVector = TRUE),
    error = function(e) NULL
  )
  if (is.null(provenance) || !identical(provenance$config_sha256, expected_config_hash)) {
    return(FALSE)
  }

  files <- tryCatch(
    read.csv(file_manifest_path, stringsAsFactors = FALSE),
    error = function(e) NULL
  )
  if (is.null(files) || !all(c("relative_path", "bytes", "sha256") %in% names(files))) {
    return(FALSE)
  }
  paths <- file.path(bundle_dir, files$relative_path)
  if (!all(file.exists(paths))) return(FALSE)
  if (!all(as.numeric(file.info(paths)$size) == files$bytes)) return(FALSE)
  observed <- vapply(paths, sha256_file, character(1))
  identical(unname(observed), unname(files$sha256))
}

write_csv_stable <- function(x, path) {
  utils::write.csv(x, path, row.names = FALSE, quote = TRUE, na = "")
}

write_bundle <- function(
  seed_id,
  seed_manifest,
  seed_manifest_path,
  output_root,
  force = FALSE,
  verify_legacy = identical(seed_id, "SIM01")
) {
  ledger <- effective_ledger_for(seed_manifest, seed_id)
  generation_rows <- ledger[ledger$component %in% .canonical_required_seed_components, , drop = FALSE]
  missing_generation <- setdiff(.canonical_required_seed_components, generation_rows$component)
  if (length(missing_generation)) {
    stop(
      seed_id, " lacks generation seed component(s): ",
      paste(missing_generation, collapse = ", "),
      call. = FALSE
    )
  }
  generation_seeds <- setNames(
    generation_rows$effective_seed,
    generation_rows$component
  )[.canonical_required_seed_components]

  hidden_row <- ledger[ledger$component == "hidden_reference", , drop = FALSE]
  if (nrow(hidden_row) != 1L) {
    stop(seed_id, " must have exactly one hidden_reference seed.", call. = FALSE)
  }

  core_path <- file.path(dirname(script_path), "simulation_core.R")
  writer_path <- script_path
  config_record <- list(
    bundle_format_version = "1.0.0",
    seed_id = seed_id,
    seed_manifest_sha256 = sha256_file(seed_manifest_path),
    simulation_core_sha256 = sha256_file(core_path),
    bundle_writer_sha256 = sha256_file(writer_path),
    declared_and_effective_seed_ledger = ledger[
      , c("component", "declared_seed", "effective_seed", "seed_source"), drop = FALSE
    ],
    save_format = list(matrix = "RDS version 3, gzip", table = "quoted CSV")
  )
  config_hash <- sha256_object(config_record)
  bundle_dir <- file.path(output_root, seed_id)

  if (dir.exists(bundle_dir) && validate_existing_bundle(bundle_dir, config_hash)) {
    message(seed_id, ": existing bundle passed hashes and config validation; reusing it.")
    return(invisible(bundle_dir))
  }
  if (dir.exists(bundle_dir) && !force) {
    stop(
      seed_id, ": an existing bundle failed validation or has a different config. ",
      "Re-run with --force to archive and replace it.",
      call. = FALSE
    )
  }

  dir.create(output_root, recursive = TRUE, showWarnings = FALSE)
  temporary_dir <- file.path(
    output_root,
    paste0(".", seed_id, ".tmp-", Sys.getpid())
  )
  if (dir.exists(temporary_dir)) {
    stop("Temporary bundle directory already exists: ", temporary_dir, call. = FALSE)
  }
  dir.create(temporary_dir, recursive = FALSE, showWarnings = FALSE)
  committed <- FALSE
  on.exit({
    if (!committed && dir.exists(temporary_dir)) {
      unlink(temporary_dir, recursive = TRUE, force = TRUE)
    }
  }, add = TRUE)

  simulation <- generate_canonical_simulation(
    generation_seeds,
    include_artifact_matrices = FALSE
  )
  hidden_assignment <- select_canonical_hidden_references(
    simulation$metadata,
    seed = hidden_row$effective_seed,
    hidden_per_plate = 2L
  )

  standardized_metadata <- simulation$metadata
  standardized_metadata$batch <- standardized_metadata$plate
  standardized_metadata$within_batch_order <- standardized_metadata$order_in_plate
  standardized_metadata$class <- ifelse(
    standardized_metadata$sample_type == "control", "QC", "Study"
  )
  standardized_metadata$is_qc <- standardized_metadata$sample_type == "control"
  standardized_metadata$is_hidden_reference <- standardized_metadata$sample_id %in%
    hidden_assignment$sample_id[hidden_assignment$is_hidden_reference]
  standardized_metadata$reference_role <- "not_a_control"
  standardized_metadata$reference_role[standardized_metadata$is_qc] <- "training_control"
  standardized_metadata$reference_role[standardized_metadata$is_hidden_reference] <- "hidden_test"

  saveRDS(
    simulation$raw_intensity,
    file.path(temporary_dir, "raw_intensity.rds"),
    version = 3,
    compress = "gzip"
  )
  saveRDS(
    simulation$clean_ground_truth,
    file.path(temporary_dir, "clean_ground_truth.rds"),
    version = 3,
    compress = "gzip"
  )
  write_csv_stable(standardized_metadata, file.path(temporary_dir, "sample_metadata.csv"))
  write_csv_stable(simulation$feature_truth, file.path(temporary_dir, "feature_truth.csv"))
  write_csv_stable(
    simulation$feature_plate_truth,
    file.path(temporary_dir, "feature_plate_truth.csv")
  )
  write_csv_stable(
    hidden_assignment,
    file.path(temporary_dir, "hidden_reference_assignment.csv")
  )
  write_csv_stable(
    ledger[
      , c(
        "workstream", "seed_id", "display_realization", "component",
        "declared_seed", "effective_seed", "seed_source",
        "prespecified_before_pilot"
      ),
      drop = FALSE
    ],
    file.path(temporary_dir, "seed_ledger.csv")
  )
  jsonlite::write_json(
    simulation$design_parameters,
    file.path(temporary_dir, "design_parameters.json"),
    auto_unbox = TRUE,
    pretty = TRUE,
    digits = NA
  )

  legacy_validation <- data.frame(
    seed_id = seed_id,
    check = c(
      "raw_numeric_and_dimnames", "clean_numeric_and_dimnames",
      "metadata_legacy_columns", "feature_design_legacy_columns"
    ),
    tolerance = c(1e-12, 1e-12, 0, 0),
    max_abs_difference = NA_real_,
    dimnames_identical = NA,
    values_identical = NA,
    passed = NA,
    stringsAsFactors = FALSE
  )

  if (verify_legacy) {
    read_legacy_matrix <- function(path) {
      x <- utils::read.delim(path, check.names = FALSE, stringsAsFactors = FALSE)
      ids <- x[[1L]]
      out <- as.matrix(x[-1L])
      storage.mode(out) <- "double"
      rownames(out) <- ids
      out
    }
    legacy_raw <- read_legacy_matrix(file.path(repo_root, "data", "simulated", "shifted_profiles.tsv"))
    legacy_clean <- read_legacy_matrix(file.path(repo_root, "data", "simulated", "ground_truth.tsv"))
    legacy_metadata <- utils::read.delim(
      file.path(repo_root, "data", "simulated", "sample_metadata.tsv"),
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
    legacy_design <- utils::read.delim(
      file.path(repo_root, "data", "simulated", "simulation_design_table.tsv"),
      stringsAsFactors = FALSE,
      check.names = FALSE
    )

    matrix_check <- function(observed, expected, tolerance) {
      same_names <- identical(dimnames(observed), dimnames(expected))
      same_dimensions <- identical(dim(observed), dim(expected))
      difference <- if (same_dimensions) max(abs(observed - expected)) else Inf
      c(
        max_abs_difference = difference,
        dimnames_identical = same_names,
        values_identical = same_dimensions && isTRUE(difference == 0),
        passed = same_dimensions && same_names && is.finite(difference) && difference <= tolerance
      )
    }
    raw_check <- matrix_check(simulation$raw_intensity, legacy_raw, 1e-12)
    clean_check <- matrix_check(simulation$clean_ground_truth, legacy_clean, 1e-12)

    legacy_metadata_columns <- names(legacy_metadata)
    metadata_equal <- identical(
      simulation$metadata[, legacy_metadata_columns, drop = FALSE],
      legacy_metadata
    )
    legacy_design_columns <- names(legacy_design)
    design_equal <- identical(
      simulation$feature_truth[, legacy_design_columns, drop = FALSE],
      legacy_design
    )

    legacy_validation$max_abs_difference[1:2] <- c(
      raw_check[["max_abs_difference"]], clean_check[["max_abs_difference"]]
    )
    legacy_validation$dimnames_identical[1:2] <- as.logical(c(
      raw_check[["dimnames_identical"]], clean_check[["dimnames_identical"]]
    ))
    legacy_validation$values_identical <- c(
      as.logical(raw_check[["values_identical"]]),
      as.logical(clean_check[["values_identical"]]),
      metadata_equal,
      design_equal
    )
    legacy_validation$passed <- c(
      as.logical(raw_check[["passed"]]),
      as.logical(clean_check[["passed"]]),
      metadata_equal,
      design_equal
    )
  } else {
    legacy_validation$check <- paste0("not_applicable::", legacy_validation$check)
    legacy_validation$passed <- TRUE
  }
  write_csv_stable(
    legacy_validation,
    file.path(temporary_dir, "legacy_equivalence_validation.csv")
  )
  if (!all(legacy_validation$passed)) {
    stop(
      seed_id, " failed historical simulation equivalence validation: ",
      paste(legacy_validation$check[!legacy_validation$passed], collapse = ", "),
      call. = FALSE
    )
  }

  provenance <- list(
    bundle_format_version = "1.0.0",
    seed_id = seed_id,
    display_realization = isTRUE(ledger$display_realization[[1L]]),
    created_at = format(Sys.time(), "%Y-%m-%dT%H:%M:%S%z"),
    config_sha256 = config_hash,
    source_seed_manifest = sub(paste0("^", repo_root, "/?"), "", seed_manifest_path),
    source_seed_manifest_sha256 = sha256_file(seed_manifest_path),
    simulation_core = sub(paste0("^", repo_root, "/?"), "", core_path),
    simulation_core_sha256 = sha256_file(core_path),
    bundle_writer = sub(paste0("^", repo_root, "/?"), "", writer_path),
    bundle_writer_sha256 = sha256_file(writer_path),
    dimensions = list(
      features = nrow(simulation$raw_intensity),
      injections = ncol(simulation$raw_intensity),
      plates = length(unique(simulation$metadata$plate)),
      controls = sum(simulation$metadata$sample_type == "control"),
      study_injections = sum(simulation$metadata$sample_type == "sample"),
      hidden_references = sum(hidden_assignment$is_hidden_reference)
    ),
    object_sha256 = list(
      raw_intensity = sha256_object(simulation$raw_intensity),
      clean_ground_truth = sha256_object(simulation$clean_ground_truth),
      metadata_core = sha256_object(simulation$metadata),
      feature_truth = sha256_object(simulation$feature_truth),
      feature_plate_truth = sha256_object(simulation$feature_plate_truth),
      hidden_reference_assignment = sha256_object(hidden_assignment)
    ),
    sim01_seed_note = if (identical(seed_id, "SIM01")) {
      paste(
        "The six effective generator seeds reproduce the historical display",
        "realization; their different declared robustness-ledger seeds are",
        "retained beside them in seed_ledger.csv. Hidden-reference and method",
        "seeds use the prespecified ledger unchanged."
      )
    } else {
      "Not applicable: declared and effective generator seeds are identical."
    },
    legacy_equivalence_required = isTRUE(verify_legacy),
    legacy_equivalence_passed = all(legacy_validation$passed),
    R = list(version = R.version.string, platform = R.version$platform)
  )
  jsonlite::write_json(
    provenance,
    file.path(temporary_dir, "bundle_provenance.json"),
    auto_unbox = TRUE,
    pretty = TRUE,
    digits = NA
  )

  persisted_files <- list.files(temporary_dir, full.names = TRUE, recursive = FALSE)
  persisted_files <- persisted_files[basename(persisted_files) != "bundle_files.csv"]
  persisted_files <- sort(persisted_files)
  file_manifest <- data.frame(
    relative_path = basename(persisted_files),
    bytes = as.numeric(file.info(persisted_files)$size),
    sha256 = vapply(persisted_files, sha256_file, character(1)),
    stringsAsFactors = FALSE
  )
  write_csv_stable(file_manifest, file.path(temporary_dir, "bundle_files.csv"))

  if (dir.exists(bundle_dir)) {
    archive_dir <- file.path(
      output_root,
      paste0(seed_id, ".replaced-", format(Sys.time(), "%Y%m%dT%H%M%S"))
    )
    if (!file.rename(bundle_dir, archive_dir)) {
      stop("Could not archive existing bundle to: ", archive_dir, call. = FALSE)
    }
    message(seed_id, ": archived previous invalid bundle at ", archive_dir)
  }
  if (!file.rename(temporary_dir, bundle_dir)) {
    stop("Could not atomically commit bundle to: ", bundle_dir, call. = FALSE)
  }
  committed <- TRUE

  if (!validate_existing_bundle(bundle_dir, config_hash)) {
    stop(seed_id, ": committed bundle failed post-write validation.", call. = FALSE)
  }
  message(
    seed_id, ": wrote canonical bundle (",
    nrow(simulation$raw_intensity), " features x ",
    ncol(simulation$raw_intensity), " injections; ",
    sum(hidden_assignment$is_hidden_reference), " hidden references)."
  )
  invisible(bundle_dir)
}

parse_cli <- function(args) {
  options <- list(seed_ids = character(), all = FALSE, force = FALSE, verify_legacy = TRUE)
  for (arg in args) {
    if (identical(arg, "--all")) {
      options$all <- TRUE
    } else if (identical(arg, "--force")) {
      options$force <- TRUE
    } else if (identical(arg, "--no-legacy-check")) {
      options$verify_legacy <- FALSE
    } else if (startsWith(arg, "--seed-id=")) {
      options$seed_ids <- c(options$seed_ids, sub("^--seed-id=", "", arg))
    } else if (grepl("^SIM[0-9]{2}$", arg)) {
      options$seed_ids <- c(options$seed_ids, arg)
    } else if (arg %in% c("-h", "--help")) {
      cat(
        "Usage: Rscript scripts/robustness/generate_simulation_bundles.R ",
        "[--seed-id=SIM01 | SIM01 ... | --all] [--force] [--no-legacy-check]\n",
        sep = ""
      )
      quit(save = "no", status = 0L)
    } else {
      stop("Unknown argument: ", arg, call. = FALSE)
    }
  }
  options
}

if (sys.nframe() == 0L) {
  setwd(repo_root)
  cli <- parse_cli(commandArgs(trailingOnly = TRUE))
  seed_manifest_path <- file.path(
    repo_root, "results", "robustness", "00_provenance", "seed_manifest.csv"
  )
  seed_manifest <- read_seed_manifest(seed_manifest_path)
  available_ids <- unique(seed_manifest$seed_id[
    seed_manifest$workstream == "canonical_repeated_simulation"
  ])
  seed_ids <- if (cli$all) available_ids else unique(cli$seed_ids)
  if (!length(seed_ids)) seed_ids <- "SIM01"
  unknown <- setdiff(seed_ids, available_ids)
  if (length(unknown)) {
    stop("Unknown canonical simulation seed ID(s): ", paste(unknown, collapse = ", "))
  }

  output_root <- file.path(
    repo_root, "results", "robustness", "03_canonical_simulation", "bundles"
  )
  for (seed_id in seed_ids) {
    write_bundle(
      seed_id = seed_id,
      seed_manifest = seed_manifest,
      seed_manifest_path = seed_manifest_path,
      output_root = output_root,
      force = cli$force,
      verify_legacy = cli$verify_legacy && identical(seed_id, "SIM01")
    )
  }
}
